---
- hosts: localhost
  roles:
    - { role: common, tags: common}
    - { role: i3, tags: i3}
    - { role: dotfiles, tags: dotfiles}
    - { role: vim, tags: vim}
    - { role: misc, tags: misc}
    - { role: syncthing, tags: syncthing}
    - { role: asdf, tags: asdf}
