---

- name: dotfiles | install software
  apt:
    name: [tmux, vim-gtk, zsh, exuberant-ctags]
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"

- name: dotfiles | create backup directory
  file: path=~/.backups state=directory

- name: dotfiles | check for non-symlink originals
  stat: path="~/{{ item }}"
  register: original_check
  loop: '{{dotfile_files + dotfile_templates}}'
  changed_when: original_check.stat.exists and not original_check.stat.islnk

- name: dotfiles | show original_check
  debug:
    var: original_check
    verbosity: 2

- name: dotfiles | backup originals
  command:
    mv ~/{{ item.0 }} ~/.backups/
    creates=~/.backups/{{ item.0 }}
    removes=~/{{ item.0 }}
  loop:
    '{{ (dotfile_files + dotfile_templates) | zip(original_check.results) | list }}'
  when: item.1.stat.exists and not item.1.stat.islnk
  loop_control:
    label: '{{item.0}}'

- name: dotfiles | create symlinks
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  loop: '{{dotfile_files}}'

- name: dotfiles | create symlinks for sshrc
  file: src=~/{{ item }}
        path=~/.sshrc.d/{{ item }}
        state=link
        force=yes
  loop: '{{sshrc_symlink}}'

# Provide an extension point for other roles to dump .zshenv stuff into.
- name: dotfiles | make ~/.zshenv.d
  file: path=~/.zshenv.d state=directory

- name: dotfiles | rebuild fonts
  command:
    fc-cache -f -v
