---

- name: i3 | install packages
  apt:
    name: [i3, dunst, i3lock, i3status, suckless-tools, shutter, xautolock, rxvt-unicode, xclip, rofi]
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"

- name: i3 | install config file i3
  file: src={{ i3_config_path }}
        path=~/.config/i3
        force=yes
        state=link

- name: i3 | install config file rofi
  file: src={{ rofi_config_path }}
        path=~/.config/rofi
        force=yes
        state=link

- name: i3 | install config file dunst
  file: src={{ dunst_config_path }}
        path=~/.dunstrc
        force=yes
        state=link

- name: i3 | install config file urxvt
  file: src={{ xdefaults_config_path }}
        path=~/.Xdefaults
        force=yes
        state=link

- name: i3 | install keyboards
  file: src={{ keyboard_config_path }}
        path={{ keyboard_system_path }}
        force=yes
        state=hard
        owner=root
        group=root
        mode=644
  become: yes
  notify: i3 | reload xorg config
