---

- name: common | Install packages
  apt:
    name: [git, gitk, htop, make, curl, keychain, openssh-client, most, snapd]
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
